"""tipo checklist modo ia convencional

Revision ID: 0ceb75b528f9
Revises: e5e52aab256f
Create Date: 2026-04-30 19:21:25.347605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ceb75b528f9'
down_revision: Union[str, None] = 'e5e52aab256f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checklist_items', sa.Column('modo_ia', sa.Enum('foto_referencia', 'prompt', 'ambas', 'ninguna', name='modoia'), nullable=False))
    op.add_column('checklist_items', sa.Column('prompt_referencia', sa.Text(), nullable=True))
    op.add_column('checklist_items', sa.Column('permite_foto', sa.Boolean(), nullable=False))
    op.add_column('respuestas', sa.Column('texto_respuesta', sa.Text(), nullable=True))
    op.add_column('respuestas', sa.Column('foto_opcional_url', sa.String(length=500), nullable=True))
    op.add_column('respuestas', sa.Column('completado', sa.Boolean(), nullable=False))
    op.alter_column('respuestas', 'foto_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('respuestas', 'foto_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.drop_column('respuestas', 'completado')
    op.drop_column('respuestas', 'foto_opcional_url')
    op.drop_column('respuestas', 'texto_respuesta')
    op.drop_column('checklist_items', 'permite_foto')
    op.drop_column('checklist_items', 'prompt_referencia')
    op.drop_column('checklist_items', 'modo_ia')
    # ### end Alembic commands ###
