"""agregar empresas codigos y empresa_id en users

Revision ID: 1449c1d58a4e
Revises: fa94080da983
Create Date: 2026-04-01 12:21:21.737384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1449c1d58a4e'
down_revision: Union[str, None] = 'fa94080da983'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
