"""agregar es_principal en users

Revision ID: a33a8ffdc98b
Revises: 6dd9284e0336
Create Date: 2026-04-10 11:42:12.421986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a33a8ffdc98b'
down_revision: Union[str, None] = '6dd9284e0336'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
