"""fix fk codigos_invitacion

Revision ID: d7571af81f90
Revises: 1449c1d58a4e
Create Date: 2026-04-01 16:14:40.074067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7571af81f90'
down_revision: Union[str, None] = '1449c1d58a4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'codigos_invitacion', 'empresas', ['empresa_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'codigos_invitacion', type_='foreignkey')
    # ### end Alembic commands ###
