"""agregar empresas codigos y empresa_id en users

Revision ID: fa94080da983
Revises: 13d1180e6338
Create Date: 2026-04-01 11:24:31.854269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa94080da983'
down_revision: Union[str, None] = '13d1180e6338'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codigos_invitacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=32), nullable=False),
    sa.Column('rol_destino', sa.String(length=20), nullable=False),
    sa.Column('usado', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_codigos_invitacion_codigo'), 'codigos_invitacion', ['codigo'], unique=True)
    op.create_index(op.f('ix_codigos_invitacion_id'), 'codigos_invitacion', ['id'], unique=False)
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('email_contacto', sa.String(length=255), nullable=False),
    sa.Column('plan', sa.Enum('basico', 'premium', name='planempresa'), nullable=False),
    sa.Column('creditos_disponibles', sa.Integer(), nullable=False),
    sa.Column('creditos_mensuales', sa.Integer(), nullable=False),
    sa.Column('membresia_activa', sa.Boolean(), nullable=False),
    sa.Column('fecha_vencimiento', sa.DateTime(timezone=True), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empresas_id'), 'empresas', ['id'], unique=False)
    op.add_column('users', sa.Column('empresa_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'empresas', ['empresa_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'empresa_id')
    op.drop_index(op.f('ix_empresas_id'), table_name='empresas')
    op.drop_table('empresas')
    op.drop_index(op.f('ix_codigos_invitacion_id'), table_name='codigos_invitacion')
    op.drop_index(op.f('ix_codigos_invitacion_codigo'), table_name='codigos_invitacion')
    op.drop_table('codigos_invitacion')
    # ### end Alembic commands ###
